[build]
  command = "npm run build"
  publish = "dist"

# This is CRITICAL for React Apps.
# It redirects all traffic to index.html so React Router works.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200